
declare function krom_init(title: string, width: i32, height: i32, vsync: bool, window_mode: i32, window_features: i32, x: i32, y: i32, frequency: i32): void;
declare function krom_set_app_name(name: string): void;
declare function krom_log(v: any): void;
declare function krom_g4_clear(flags: i32, color: i32, depth: f32): void;
declare function krom_set_update_callback(callback: ()=>void): void;
declare function krom_set_drop_files_callback(callback: (file: string)=>void): void;
declare function krom_set_cut_copy_paste_callback(on_cut: ()=>string, on_copy: ()=>string, on_paste: (text: string)=>void): void;
declare function krom_set_application_state_callback(on_foreground: ()=>void, on_resume: ()=>void, on_pause: ()=>void, on_background: ()=>void, on_shutdown: ()=>void): void;
declare function krom_set_keyboard_down_callback(callback: (code: i32)=>void): void;
declare function krom_set_keyboard_up_callback(callback: (code: i32)=>void): void;
declare function krom_set_keyboard_press_callback(callback: (char_code: i32)=>void): void;
declare function krom_set_mouse_down_callback(callback: (button: i32, x: i32, y: i32)=>void): void;
declare function krom_set_mouse_up_callback(callback: (button: i32, x: i32, y: i32)=>void): void;
declare function krom_set_mouse_move_callback(callback: (x: i32, y: i32, mx: i32, my: i32)=>void): void;
declare function krom_set_mouse_wheel_callback(callback: (button: i32)=>void): void;
declare function krom_set_touch_down_callback(callback: (index: i32, x: i32, y: i32)=>void): void;
declare function krom_set_touch_up_callback(callback: (index: i32, x: i32, y: i32)=>void): void;
declare function krom_set_touch_move_callback(callback: (index: i32, x: i32, y: i32)=>void): void;
declare function krom_set_pen_down_callback(callback: (x: i32, y: i32, pressure: f32)=>void): void;
declare function krom_set_pen_up_callback(callback: (x: i32, y: i32, pressure: f32)=>void): void;
declare function krom_set_pen_move_callback(callback: (x: i32, y: i32, pressure: f32)=>void): void;
declare function krom_set_gamepad_axis_callback(callback: (gamepad: i32, axis: i32, value: f32)=>void): void;
declare function krom_set_gamepad_button_callback(callback: (gamepad: i32, button: i32, value: f32)=>void): void;
declare function krom_lock_mouse(): void;
declare function krom_unlock_mouse(): void;
declare function krom_can_lock_mouse(): bool;
declare function krom_is_mouse_locked(): bool;
declare function krom_set_mouse_position(x: i32, y: i32): void;
declare function krom_show_mouse(show: bool): void;
declare function krom_show_keyboard(show: bool): void;

declare function krom_g4_create_index_buffer(count: i32): any;
declare function krom_g4_delete_index_buffer(buffer: any): void;
declare function krom_g4_lock_index_buffer(buffer: any): Uint32Array;
declare function krom_g4_unlock_index_buffer(buffer: any): void;
declare function krom_g4_set_index_buffer(buffer: any): void;
declare function krom_g4_create_vertex_buffer(count: i32, structure: kinc_vertex_elem_t[], usage: i32, inst_data_step_rate: i32): any;
declare function krom_g4_delete_vertex_buffer(buffer: any): void;
declare function krom_g4_lock_vertex_buffer(buffer: any): ArrayBuffer;
declare function krom_g4_unlock_vertex_buffer(buffer: any): void;
declare function krom_g4_set_vertex_buffer(buffer: any): void;
declare function krom_g4_set_vertex_buffers(vertex_buffers: vertex_buffer_t[]): void;
declare function krom_g4_draw_indexed_vertices(start: i32, count: i32): void;
declare function krom_g4_draw_indexed_vertices_instanced(inst_count: i32, start: i32, count: i32): void;
declare function krom_g4_create_shader(data: ArrayBuffer, type: i32): any;
declare function krom_g4_create_vertex_shader_from_source(source: string): any;
declare function krom_g4_create_fragment_shader_from_source(source: string): any;
declare function krom_g4_delete_shader(shader: any): void;
declare function krom_g4_create_pipeline(): any;
declare function krom_g4_delete_pipeline(pipeline: any): void;
declare function krom_g4_compile_pipeline(pipeline: any, structure0: any, structure1: any, structure2: any, structure3: any, length: i32, vertex_shader: any, fragment_shader: any, geometry_shader: any, state: any): void;
declare function krom_g4_set_pipeline(pipeline: any): void;
declare function krom_load_image(file: string, readable: bool): any;
declare function krom_unload_image(image: image_t): void;
declare function krom_load_sound(file: string): any;
declare function krom_unload_sound(sound: any): void;
declare function krom_play_sound(sound: any, loop: bool): void;
declare function krom_stop_sound(sound: any): void;
declare function krom_load_blob(file: string): ArrayBuffer;
declare function krom_load_url(url: string): void;
declare function krom_copy_to_clipboard(text: string): void;

declare function krom_g4_get_constant_location(pipeline: any, name: string): any;
declare function krom_g4_get_texture_unit(pipeline: any, name: string): any;
declare function krom_g4_set_texture(stage: any, texture: any): void;
declare function krom_g4_set_render_target(stage: any, render_target: any): void;
declare function krom_g4_set_texture_depth(unit: any, texture: any): void;
declare function krom_g4_set_image_texture(stage: any, texture: any): void;
declare function krom_g4_set_texture_parameters(tex_unit: any, u_addr: i32, v_addr: i32, min_filter: i32, mag_filter: i32, mip_filter: i32): void;
declare function krom_g4_set_texture3d_parameters(tex_unit: any, u_addr: i32, v_addr: i32, w_addr: i32, min_filter: i32, mag_filter: i32, mip_filter: i32): void;
declare function krom_g4_set_bool(location: any, value: bool): void;
declare function krom_g4_set_int(location: any, value: i32): void;
declare function krom_g4_set_float(location: any, value: f32): void;
declare function krom_g4_set_float2(location: any, value1: f32, value2: f32): void;
declare function krom_g4_set_float3(location: any, value1: f32, value2: f32, value3: f32): void;
declare function krom_g4_set_float4(location: any, value1: f32, value2: f32, value3: f32, value4: f32): void;
declare function krom_g4_set_floats(location: any, values: ArrayBuffer): void;
declare function krom_g4_set_matrix4(location: any, matrix: ArrayBuffer): void;
declare function krom_g4_set_matrix3(location: any, matrix: ArrayBuffer): void;

declare function krom_get_time(): f32;
declare function krom_window_width(): i32;
declare function krom_window_height(): i32;
declare function krom_set_window_title(title: string): void;
declare function krom_get_window_mode(): i32;
declare function krom_set_window_mode(mode: i32): void;
declare function krom_resize_window(width: i32, height: i32): void;
declare function krom_move_window(x: i32, y: i32): void;
declare function krom_screen_dpi(): i32;
declare function krom_system_id(): string;
declare function krom_request_shutdown(): void;
declare function krom_display_count(): i32;
declare function krom_display_width(index: i32): i32;
declare function krom_display_height(index: i32): i32;
declare function krom_display_x(index: i32): i32;
declare function krom_display_y(index: i32): i32;
declare function krom_display_frequency(index: i32): i32;
declare function krom_display_is_primary(index: i32): bool;
declare function krom_write_storage(name: string, data: ArrayBuffer): void;
declare function krom_read_storage(name: string): ArrayBuffer;

declare function krom_g4_create_render_target(width: i32, height: i32, format: i32, depth_buffer_bits: i32, stencil_buffer_bits: i32): any;
declare function krom_g4_create_texture(width: i32, height: i32, format: i32): any;
declare function krom_g4_create_texture3d(width: i32, height: i32, depth: i32, format: i32): any;
declare function krom_g4_create_texture_from_bytes(data: ArrayBuffer, width: i32, height: i32, format: i32, readable: bool): any;
declare function krom_g4_create_texture_from_bytes3d(data: ArrayBuffer, width: i32, height: i32, depth: i32, format: i32, readable: bool): any;
declare function krom_g4_create_texture_from_encoded_bytes(data: ArrayBuffer, format: string, readable: bool): any;
declare function krom_g4_get_texture_pixels(texture: any): ArrayBuffer;
declare function krom_g4_get_render_target_pixels(render_target: any, data: ArrayBuffer): void;
declare function krom_g4_lock_texture(texture: any, level: i32): ArrayBuffer;
declare function krom_g4_unlock_texture(texture: any): void;
declare function krom_g4_clear_texture(target: any, x: i32, y: i32, z: i32, width: i32, height: i32, depth: i32, color: i32): void;
declare function krom_g4_generate_texture_mipmaps(texture: any, levels: i32): void;
declare function krom_g4_generate_render_target_mipmaps(render_target: any, levels: i32): void;
declare function krom_g4_set_mipmaps(texture: any, mipmaps: image_t[]): void;
declare function krom_g4_set_depth_from(target: any, source: any): void;
declare function krom_g4_viewport(x: i32, y: i32, width: i32, height: i32): void;
declare function krom_g4_scissor(x: i32, y: i32, width: i32, height: i32): void;
declare function krom_g4_disable_scissor(): void;
declare function krom_g4_render_targets_inverted_y(): bool;
declare function krom_g4_begin(render_target: image_t, additional: image_t[]): void;
declare function krom_g4_end(): void;
declare function krom_file_save_bytes(path: string, bytes: ArrayBuffer, length?: i32): void;
declare function krom_sys_command(cmd: string, args?: string[]): i32;
declare function krom_save_path(): string;
declare function krom_get_arg_count(): i32;
declare function krom_get_arg(index: i32): string;
declare function krom_get_files_location(): string;
declare function krom_http_request(url: string, size: i32, callback: (_: ArrayBuffer)=>void): void;

declare function krom_g2_init(image_vert: ArrayBuffer, image_frag: ArrayBuffer, colored_vert: ArrayBuffer, colored_frag: ArrayBuffer, text_vert: ArrayBuffer, text_frag: ArrayBuffer): void;
declare function krom_g2_begin(): void;
declare function krom_g2_end(): void;
declare function krom_g2_draw_scaled_sub_image(image: image_t, sx: f32, sy: f32, sw: f32, sh: f32, dx: f32, dy: f32, dw: f32, dh: f32): void;
declare function krom_g2_fill_triangle(x0: f32, y0: f32, x1: f32, y1: f32, x2: f32, y2: f32): void;
declare function krom_g2_fill_rect(x: f32, y: f32, width: f32, height: f32): void;
declare function krom_g2_draw_rect(x: f32, y: f32, width: f32, height: f32, strength: f32): void;
declare function krom_g2_draw_line(x0: f32, y0: f32, x1: f32, y1: f32, strength: f32): void;
declare function krom_g2_draw_string(text: string, x: f32, y: f32): void;
declare function krom_g2_set_font(font: any, size: i32): void;
declare function krom_g2_font_init(blob: ArrayBuffer, font_index: i32): any;
declare function krom_g2_font_13(blob: ArrayBuffer): any;
declare function krom_g2_font_set_glyphs(glyphs: i32[]): void;
declare function krom_g2_font_count(font: any): i32;
declare function krom_g2_font_height(font: any, size: i32): i32;
declare function krom_g2_string_width(font: any, size: i32, text: string): i32;
declare function krom_g2_set_bilinear_filter(bilinear: bool): void;
declare function krom_g2_restore_render_target(): void;
declare function krom_g2_set_render_target(render_target: any): void;
declare function krom_g2_set_color(color: i32): void;
declare function krom_g2_set_pipeline(pipeline: any): void;
declare function krom_g2_set_transform(matrix: ArrayBuffer): void;
declare function krom_g2_fill_circle(cx: f32, cy: f32, radius: f32, segments: i32): void;
declare function krom_g2_draw_circle(cx: f32, cy: f32, radius: f32, segments: i32, strength: f32): void;
declare function krom_g2_draw_cubic_bezier(x: f32[], y: f32[], segments: i32, strength: f32): void;

declare function krom_set_save_and_quit_callback(callback: (save: bool)=>void): void;
declare function krom_set_mouse_cursor(id: i32): void;
declare function krom_delay_idle_sleep(): void;
declare function krom_open_dialog(filter_list: string, default_path: string, open_multiple: bool): string[];
declare function krom_save_dialog(filter_list: string, default_path: string): string;
declare function krom_read_directory(path: string, foldersOnly: bool): string;
declare function krom_file_exists(path: string): bool;
declare function krom_delete_file(path: string): void;
declare function krom_inflate(bytes: ArrayBuffer, raw: bool): ArrayBuffer;
declare function krom_deflate(bytes: ArrayBuffer, raw: bool): ArrayBuffer;
declare function krom_write_jpg(path: string, bytes: ArrayBuffer, w: i32, h: i32, format: i32, quality: i32): void; // RGBA, R, RGB1, RRR1, GGG1, BBB1, AAA1
declare function krom_write_png(path: string, bytes: ArrayBuffer, w: i32, h: i32, format: i32): void;
declare function krom_encode_jpg(bytes: ArrayBuffer, w: i32, h: i32, format: i32, quality: i32): ArrayBuffer;
declare function krom_encode_png(bytes: ArrayBuffer, w: i32, h: i32, format: i32): ArrayBuffer;
declare function krom_write_mpeg(): ArrayBuffer;
declare function krom_ml_inference(model: ArrayBuffer, tensors: ArrayBuffer[], input_shape?: i32[][], output_shape?: i32[], use_gpu?: bool): ArrayBuffer;
declare function krom_ml_unload(): void;

declare function krom_raytrace_supported(): bool;
declare function krom_raytrace_init(shader: ArrayBuffer, vb: any, ib: any, scale: f32): void;
declare function krom_raytrace_set_textures(tex0: image_t, tex1: image_t, tex2: image_t, texenv: any, tex_sobol: any, tex_scramble: any, tex_rank: any): void;
declare function krom_raytrace_dispatch_rays(target: any, cb: ArrayBuffer): void;

declare function krom_window_x(): i32;
declare function krom_window_y(): i32;
declare function krom_language(): string;
declare function krom_io_obj_parse(file_bytes: ArrayBuffer, split_code: i32, start_pos: i32, udim: bool): any;

declare function krom_zui_init(ops: any): any;
declare function krom_zui_get_scale(ui: any): f32;
declare function krom_zui_set_scale(ui: any, factor: f32): void;
declare function krom_zui_set_font(ui: any, font: any): void;
declare function krom_zui_begin(ui: any): void;
declare function krom_zui_end(last: bool): void;
declare function krom_zui_begin_region(ui: any, x: i32, y: i32, w: i32): void;
declare function krom_zui_end_region(last: bool): void;
declare function krom_zui_begin_sticky(): void;
declare function krom_zui_end_sticky(): void;
declare function krom_zui_end_input(): void;
declare function krom_zui_end_window(bind_global_g: bool): void;
declare function krom_zui_end_element(element_size: f32): void;
declare function krom_zui_start_text_edit(handle: any, align: i32): void;
declare function krom_zui_input_in_rect(x: f32, y: f32, w: f32, h: f32): bool;
declare function krom_zui_window(handle: any, x: i32, y: i32, w: i32, h: i32, drag: bool): bool;
declare function krom_zui_button(text: string, align: i32, label: string): bool;
declare function krom_zui_check(handle: any, text: string, label: string): bool;
declare function krom_zui_radio(handle: any, position: i32, text: string, label: string): bool;
declare function krom_zui_combo(handle: any, texts: string[], label: string, show_label: bool, align: i32, search_bar: bool): i32;
declare function krom_zui_slider(handle: any, text: string, from: f32, to: f32, filled: bool, precision: f32, display_value: bool, align: i32, text_edit: bool): f32;
declare function krom_zui_image(image: image_t, tint: i32, h: i32, sx: i32, sy: i32, sw: i32, sh: i32): i32;
declare function krom_zui_text(text: string, align: i32, bg: i32): i32;
declare function krom_zui_text_input(handle: any, label: string, align: i32, editable: bool, live_update: bool): string;
declare function krom_zui_tab(handle: any, text: string, vertical: bool, color: i32): bool;
declare function krom_zui_panel(handle: any, text: string, isTree: bool, filled: bool, pack: bool): bool;
declare function krom_zui_handle(ops: any): any;
declare function krom_zui_separator(h: i32, fill: bool): void;
declare function krom_zui_tooltip(text: string): void;
declare function krom_zui_tooltip_image(image: image_t, max_width: i32): void;
declare function krom_zui_row(ratios: f32[]): void;
declare function krom_zui_fill(x: f32, y: f32, w: f32, h: f32, color: i32): void;
declare function krom_zui_rect(x: f32, y: f32, w: f32, h: f32, color: i32, strength: f32): void;
declare function krom_zui_draw_rect(fill: bool, x: f32, y: f32, w: f32, h: f32, strength: f32): void;
declare function krom_zui_draw_string(text: string, x_offset: f32, y_offset: f32, align: i32, truncation: bool): void;
declare function krom_zui_get_hovered_tab_name(): string;
declare function krom_zui_set_hovered_tab_name(name: string): void;
declare function krom_zui_begin_menu(): void;
declare function krom_zui_end_menu(): void;
declare function krom_zui_menu_button(text: string): bool;
declare function krom_zui_float_input(handle: any, label: string, align: i32, precision: f32): f32;
declare function krom_zui_inline_radio(handle: any, texts: string[], align: i32): i32;
declare function krom_zui_color_wheel(handle: any, alpha: bool, w: f32, h: f32, color_preview: bool, picker: ()=>void): i32;
declare function krom_zui_text_area(handle: any, align: i32, editable: bool, label: string, word_wrap: bool): string;
declare function krom_zui_text_area_coloring(packed: ArrayBuffer): void;
declare function krom_zui_nodes_init(): any;
declare function krom_zui_node_canvas(nodes: any, packed: ArrayBuffer): ArrayBuffer;
declare function krom_zui_nodes_rgba_popup(handle: any, val: ArrayBuffer, x: i32, y: i32): void;
declare function krom_zui_nodes_scale(): f32;
declare function krom_zui_nodes_pan_x(): f32;
declare function krom_zui_nodes_pan_y(): f32;
declare function krom_zui_get(ui: any, name: string): any;
declare function krom_zui_set(ui: any, name: string, val: any): void;
declare function krom_zui_handle_get(handle: any, name: string): any;
declare function krom_zui_handle_set(handle: any, name: string, val: any): void;
declare function krom_zui_handle_ptr(handle: any): i32;
declare function krom_zui_theme_init(): any;
declare function krom_zui_theme_get(theme: any, name: string): any;
declare function krom_zui_theme_set(theme: any, name: string, val: any): void;
declare function krom_zui_nodes_get(nodes: any, name: string): any;
declare function krom_zui_nodes_set(nodes: any, name: string, val: any): void;
declare function krom_zui_set_on_border_hover(f: (handle: any, side: i32)=>void): void;
declare function krom_zui_set_on_text_hover(f: ()=>void): void;
declare function krom_zui_set_on_deselect_text(f: ()=>void): void;
declare function krom_zui_set_on_tab_drop(f: (to_handle: any, to_position: i32, from_handle: any, from_position: i32)=>void): void;
declare function krom_zui_nodes_set_enum_texts(f: (node_type: string)=>string[]): void;
declare function krom_zui_nodes_set_on_custom_button(f: (node_id: i32, button_name: string)=>void): void;
declare function krom_zui_nodes_set_on_canvas_control(f: ()=>any): void;
declare function krom_zui_nodes_set_on_canvas_released(f: ()=>void): void;
declare function krom_zui_nodes_set_on_socket_released(f: (socket_id: i32)=>void): void;
declare function krom_zui_nodes_set_on_link_drag(f: (link_drag_id: i32, is_new_link: bool)=>void): void;
