name: Linux (OpenGL)

on:
  push:
    paths-ignore:
      - "README.md"
      - .github/**
      - '!.github/workflows/linux_opengl.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - .github/**
      - '!.github/workflows/linux_opengl.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup
      run: |
        sudo apt update
        sudo apt install libasound2-dev libxrandr-dev libxinerama-dev libgl1-mesa-dev libxi-dev libxcursor-dev libudev-dev libgtk-3-dev --yes --quiet
    - name: Compile
      run: |
        node Kinc/make -g opengl --compiler clang --compile
        test -e Deployment/Krom
