name: Windows (Direct3D12)

on:
  push:
    paths-ignore:
      - "README.md"
      - .github/**
      - '!.github/workflows/windows_direct3d12.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - "README.md"
      - .github/**
      - '!.github/workflows/windows_direct3d12.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Get msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Unpack v8_monolith
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: v8/libraries/win32/release/v8_monolith.7z
        pathTarget: v8/libraries/win32/release/
    - name: Apply patch
      run: git apply patch/d3d12_raytrace.diff --directory=Kinc
    - name: Compile
      run: node Kinc/make -v vs2019 -g direct3d12 --compile
